json.id lead.id
json.user_id lead.user_id
json.name lead.name
json.job_title lead.job_title
json.company lead.company
json.email_address lead.email_address
json.phone lead.phone
json.notes lead.notes
json.notes_preview lead.notes_preview
json.current_step lead.current_step
json.last_action lead.last_action
json.archived lead.archived
json.invite lead.invite
json.connection lead.connection
json.emails lead.emails
json.meeting lead.meeting
json.interviews lead.interviews
json.offers lead.offers
