json.id application.id
json.user_id application.user_id
json.job_title application.job_title
json.company application.company
json.notes application.notes
json.notes_preview application.notes_preview
json.current_step application.current_step
json.last_action application.last_action
json.archived application.archived
json.invite application.submission
json.interviews application.interviews
json.offers application.offers
